### ISSUE TITLE
7. Add support for python

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#297] opened 2018-08-19 20:36 UTC
Adding support for Python so something like:
```
tau init <tags selection>
tau python ./a.py app_args
```
translates to:
```
tau_python -T tags a.py —tau-python-args=app_args
```

**Comment by zbeekman** [comment] 2018-10-24 16:15
From Sameer's email:

>7. Adding support for Python so something like:
>
>tau init <tags selection>
>tau python ./a.py app_args
>translates to:
>tau_python -T tags a.py —tau-python-args=app_args

**Comment by zbeekman** [comment] 2018-10-24 16:35
#265 is a duplicate of this issue

**Comment by zbeekman** [comment] 2018-10-24 17:12
Closing #265 as a duplicate of this issue.

Nick said:

> Support Python applications, so that we could do
> 
> > tau python foo.py
> 
> to invoke tau_python on foo.py. Since Python support in TAU is version specific, we will need to verify that we have a TAU configuration for the specific version of Python being used and build one as necessary.

**Comment by zbeekman** [comment] 2018-10-24 17:12
Then sameer said:

> Hi,
> 	How should we support python3 on systems where python in your path is not a symlink to python3? Like on a Mac. 
> 	Should we introduce tau_python3? An argument to tau_python to specify version or interpreter name? Will it make it uglier? Would we want something like:
> tau python3 foo.py 34 52
> to invoke python3 and
> tau python foo.py 34 52
> 	to invoke python in your path? Meaning tau_python internally calls python?

**Comment by devinshende** [comment] 2019-07-15 19:06
Added in 13222d884e32faabc030ff043d71146c5f2bcc9c

**Closed by devinshende** 2019-07-15 19:06 UTC
Labels: enhancement, help wanted
