### ISSUE TITLE
Make install fails on Onyx (unstable)

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#202] opened 2017-10-06 19:37 UTC
Here's how to reproduce

```bash
module swap PrgEnv-cray PrgEnv-intel
git clone https://github.com/ParaToolsInc/taucmdr && cd taucmdr
git checkout unstable
make install

...

[TAU] Compiling libunwind...
[TAU] Completed in 0.261 seconds                                                                                                                                        make[3]: *** [mi/Gdestroy_addr_space.lo] Error 1
Makefile:3204: recipe for target 'mi/Gset_fpreg.lo' failed
make[3]: *** [mi/Gset_fpreg.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Gpe.lo' failed
make[3]: *** [dwarf/Gpe.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Gfind_proc_info-lsb.lo' failed
make[3]: *** [dwarf/Gfind_proc_info-lsb.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Gstep.lo' failed
make[3]: *** [x86_64/Gstep.lo] Error 1
Makefile:3204: recipe for target 'mi/Gget_fpreg.lo' failed
make[3]: *** [mi/Gget_fpreg.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Gparser.lo' failed
make[3]: *** [dwarf/Gparser.lo] Error 1
Makefile:3204: recipe for target 'mi/Gput_dynamic_unwind_info.lo' failed
make[3]: *** [mi/Gput_dynamic_unwind_info.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Gget_save_loc.lo' failed
make[3]: *** [x86_64/Gget_save_loc.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Gtrace.lo' failed
make[3]: *** [x86_64/Gtrace.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Gfde.lo' failed
make[3]: *** [dwarf/Gfde.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Gresume.lo' failed
make[3]: *** [x86_64/Gresume.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Gexpr.lo' failed
make[3]: *** [dwarf/Gexpr.lo] Error 1
Makefile:3204: recipe for target 'mi/init.lo' failed
make[3]: *** [mi/init.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Gregs.lo' failed
make[3]: *** [x86_64/Gregs.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Gfind_unwind_table.lo' failed
make[3]: *** [dwarf/Gfind_unwind_table.lo] Error 1
Makefile:3204: recipe for target 'x86_64/is_fpreg.lo' failed
make[3]: *** [x86_64/is_fpreg.lo] Error 1
Makefile:3204: recipe for target 'mi/flush_cache.lo' failed
make[3]: *** [mi/flush_cache.lo] Error 1
Makefile:3204: recipe for target 'mi/strerror.lo' failed
make[3]: *** [mi/strerror.lo] Error 1
Makefile:3204: recipe for target 'x86_64/regname.lo' failed
make[3]: *** [x86_64/regname.lo] Error 1
Makefile:3204: recipe for target 'mi/mempool.lo' failed
make[3]: *** [mi/mempool.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Los-linux.lo' failed
make[3]: *** [x86_64/Los-linux.lo] Error 1
make[3]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:1331: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:476: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1'
[TAU] Completed in 0.115 seconds                                                                                                                                        make[1]: Entering directory '/dev/shm/tmpKsqpHB/libunwind-1.1'
Making all in src
make[2]: Entering directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
make  all-am
make[3]: Entering directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
source='os-linux.c' object='os-linux.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../config/depcomp \
/bin/sh ../libtool --tag=CC   --mode=compile /opt/cray/pe/craype/2.5.12/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -I../include/tdep-x86_64 -I. -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -c -o os-linux.lo os-linux.c
libtool: compile:  /opt/cray/pe/craype/2.5.12/bin/cc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-x86_64 -I. -D_GNU_SOURCE -DNDEBUG -fPIC -fexceptions -Wall -Wsign-compare -c os-linux.c -o os-linux.o
CC-2119 craycc: ERROR in command line
  The phase argument or the comma before the phase argument is missing for the -W option.
CC-2119 craycc: ERROR in command line
  The phase argument or the comma before the phase argument is missing for the -W option.
Makefile:3204: recipe for target 'os-linux.lo' failed
make[3]: *** [os-linux.lo] Error 1
make[3]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:1331: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:476: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1'
[TAU] Installing libunwind...
[TAU] Completed in 0.251 seconds                                                                                                                                        make[3]: *** [mi/Lget_reg.lo] Error 1
Makefile:3204: recipe for target 'mi/Ldyn-extract.lo' failed
make[3]: *** [mi/Ldyn-extract.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Lresume.lo' failed
make[3]: *** [x86_64/Lresume.lo] Error 1
Makefile:3204: recipe for target 'mi/Lset_caching_policy.lo' failed
make[3]: *** [mi/Lset_caching_policy.lo] Error 1
Makefile:3204: recipe for target 'x86_64/is_fpreg.lo' failed
make[3]: *** [x86_64/is_fpreg.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Linit.lo' failed
make[3]: *** [x86_64/Linit.lo] Error 1
Makefile:3204: recipe for target 'mi/Lget_fpreg.lo' failed
make[3]: *** [mi/Lget_fpreg.lo] Error 1
Makefile:3204: recipe for target 'mi/Lset_reg.lo' failed
make[3]: *** [mi/Lset_reg.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Lfde.lo' failed
make[3]: *** [dwarf/Lfde.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Lget_proc_info.lo' failed
make[3]: *** [x86_64/Lget_proc_info.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Lstep.lo' failed
make[3]: *** [x86_64/Lstep.lo] Error 1
Makefile:3204: recipe for target 'mi/mempool.lo' failed
make[3]: *** [mi/mempool.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Linit_local.lo' failed
make[3]: *** [x86_64/Linit_local.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Lcreate_addr_space.lo' failed
make[3]: *** [x86_64/Lcreate_addr_space.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Lregs.lo' failed
make[3]: *** [x86_64/Lregs.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Lpe.lo' failed
make[3]: *** [dwarf/Lpe.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Lexpr.lo' failed
make[3]: *** [dwarf/Lexpr.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Ltrace.lo' failed
make[3]: *** [x86_64/Ltrace.lo] Error 1
Makefile:3204: recipe for target 'x86_64/Linit_remote.lo' failed
make[3]: *** [x86_64/Linit_remote.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Lstep.lo' failed
make[3]: *** [dwarf/Lstep.lo] Error 1
Makefile:3204: recipe for target 'dwarf/Lparser.lo' failed
make[3]: *** [dwarf/Lparser.lo] Error 1
Makefile:3204: recipe for target 'mi/Lset_fpreg.lo' failed
make[3]: *** [mi/Lset_fpreg.lo] Error 1
make[3]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:3339: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:476: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1'
[TAU] Completed in 0.166 seconds                                                                                                                                        make[1]: Entering directory '/dev/shm/tmpKsqpHB/libunwind-1.1'
Making install in src
make[2]: Entering directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
make  install-am
make[3]: Entering directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
source='os-linux.c' object='os-linux.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../config/depcomp \
/bin/sh ../libtool --tag=CC   --mode=compile /opt/cray/pe/craype/2.5.12/bin/cc -DHAVE_CONFIG_H -I. -I../include  -I../include -I../include/tdep-x86_64 -I. -D_GNU_SOURCE -DNDEBUG  -fPIC -fexceptions -Wall -Wsign-compare -c -o os-linux.lo os-linux.c
libtool: compile:  /opt/cray/pe/craype/2.5.12/bin/cc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-x86_64 -I. -D_GNU_SOURCE -DNDEBUG -fPIC -fexceptions -Wall -Wsign-compare -c os-linux.c -o os-linux.o
CC-2119 craycc: ERROR in command line
  The phase argument or the comma before the phase argument is missing for the -W option.
CC-2119 craycc: ERROR in command line
  The phase argument or the comma before the phase argument is missing for the -W option.
Makefile:3204: recipe for target 'os-linux.lo' failed
make[3]: *** [os-linux.lo] Error 1
make[3]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:3339: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1/src'
Makefile:476: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/dev/shm/tmpKsqpHB/libunwind-1.1'
[TAU] libunwind installation failed: libunwind installation failed
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU]
[TAU] CRITICAL
[TAU]
[TAU] libunwind installation failed
[TAU]
[TAU] Hint: Try `configure --help`
[TAU]
[TAU] Please check the selected experiment or send '/p/home/zbeekman/.local/taucmdr/debug_log' to <support@paratools.com> for assistance.
[TAU]
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] ******************************************************************************************************************************************************************
[TAU]
[TAU] WARNING
[TAU]
[TAU] The following temporary directories were not deleted due to build errors: /dev/shm/tmpKsqpHB/libunwind-1.1, /dev/shm/tmpKsqpHB/libunwind-1.1.
[TAU]
[TAU] ******************************************************************************************************************************************************************
Makefile:160: recipe for target 'install' failed
make: *** [install] Error 156
```

**Comment by zbeekman** [comment] 2017-10-06 19:49
OK, it's possible I may have had PrgEnv-cray loaded, NOT PrgEnv-intel... trying to build with GNU now, will double check Intel again later.

**Comment by jlinford** [comment] 2017-10-06 20:42
Ya, I can't reproduce this.  It works for me with PrgEnv-Intel.  I see Cray compilers in your log.  :-)

**Comment by zbeekman** [comment] 2017-10-06 21:06
Doh! One of these days I'll learn to manage my environment properly

**Comment by jlinford** [comment] 2017-10-06 21:16
`make install` is working out-of-the-box for me as of 8fededebd868b2cf3ea816837098e266dc561b9a.  There was an issue with the UPC compiler wrapper, but that's fixed now.

**Closed by jlinford** 2017-10-06 21:16 UTC

**Comment by jlinford** [comment] 2017-10-06 21:34
FYI, 2128a0d74833bf8443246202516852138721a723 stops TAU Commander from trying to build anything when PrgEnv-cray is loaded.  Give it a try!

**Comment by zbeekman** [comment] 2017-10-06 21:44
Zaak proofing. I like it!
