### ISSUE TITLE
(2.) When using -tau=<path>, TAU downloaded anyways

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#285] opened 2018-05-30 01:29 UTC
Sameer reports that when using -tau=<path>, using e.g. `tau show` will still download the release TAU and use its tools to do the display

**Comment by zbeekman** [comment] 2018-10-24 16:08
Corresponds to:

>2. TAU Commander installation. Currently, when I use:
make install INSTALLDIR=<prefix>  TAU=/path/to/my/tau
we need to check if it makes the symlink properly. I recall seeing a tau-2.27 directory somewhere and a weird error when I used:
>
>tau show
	and instead of using the paraprof from /path/to/my/tau, it started building tau 2.27 and then launching paraprof from there. 

From Sameer's email

**Comment by zbeekman** [comment] 2018-10-24 17:16
Closing as duplicate of #292

**Closed** 2018-10-24 17:16 UTC
Labels: bug, duplicate
