### ISSUE TITLE
(7.) Support Python applications

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#265] opened 2018-04-09 16:29 UTC
Support Python applications, so that we could do

> tau python foo.py

to invoke tau_python on foo.py. Since Python support in TAU is version specific, we will need to verify that we have a TAU configuration for the specific version of Python being used and build one as necessary.

**Comment by zbeekman** [comment] 2018-10-24 17:13
Duplicate of #297

**Closed by zbeekman** 2018-10-24 17:13 UTC
Labels: duplicate, enhancement
