### ISSUE TITLE
fails to install on copper

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#158] opened 2017-05-12 17:09 UTC
[debug_log-copper.txt](https://github.com/ParaToolsInc/taucmdr/files/997427/debug_log-copper.txt)

Very careful to make sure this was a clean build - everything else entirely removed - history below:
    38  11:35   rm -rf .tau
    39  11:35   cd $PET_HOME
    40  11:35   ls
    41  11:35   cd pkgs
    42  11:35   ls
    43  11:35   ls -lt
    44  11:36   rm -rf taucmdr-e859a221/
    45  11:36   cd
    46  11:36   ls -lt
    47  11:36   rm -rf taucmdr
    48  11:36   module list
    49  11:36   module unload PrgEnv-pgi
    50  11:36   module load PrgEnv-intel
    51  11:36   module load cray-shmem
    52  11:37   git clone https://github.com/ParaToolsInc/taucmdr.git
    53  11:37   cd taic,dr
    54  11:37   cd taucmdr
    55  11:38   ./configure --prefix=$PET_HOME/pkgs/taucmdr-e859a221
    56  11:39   make install

[TAU] TAU Performance System installation failed: TAU compilation/installation
[TAU]     failed
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU]
[TAU] CRITICAL
[TAU]
[TAU] TAU compilation/installation failed

**Comment by jlinford** [comment] 2017-05-12 17:34
Once again, this is a TAU (not tau commander) bug.  Please look carefully at the instructions I sent in an e-mail titled "Update for taucmdr+SHMEM" and reproduced below.  Because of the bugs in TAU's current release, you must follow those instructions or TAU will fail to build.

> On Cray load the PrgEnv-intel and cray-shmem modules.
> On other systems use the default Intel compilers however they're provided.
> 
> cd taucmdr
> git checkout master
> git pull
> make clean
> curl http://fs.paratools.com/tau-nightly.tgz > packages/tau.tgz
> ./configure --prefix=$PET_HOME/pkgs/taucmdr-1.0
> make install
>
> The `curl` command will cause taucmdr to treat the nightly release as a stable release with SHMEM bug fixes.

Thanks!

**Comment by jlinford** [comment] 2017-05-12 18:28
I'm closing this issue since the debug log shows you're not using TAU's nightly build with SHMEM bug fixes.  I'll respond to Issue #148 where nightly was used.

**Closed by jlinford** 2017-05-12 18:28 UTC
Labels: duplicate
